<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						color: #333;
						margin: 0;
					}
					#top {
						background-color: #f1f1f1;
						padding: 20px 30px;
						border-bottom: 1px solid #ddd;
					}
					#top h1 {
						margin: 0;
						font-size: 24px;
						color: #333;
					}
					#top p {
						margin: 10px 0 0;
						font-size: 14px;
						color: #555;
					}
					#top p a {
						color: #800080;
						text-decoration: none;
					}
					#top p a:hover {
						text-decoration: underline;
					}
					#content {
						padding: 20px 30px;
						max-width: 1000px;
						margin: 0 auto;
					}
					table {
						width: 100%;
						border-collapse: collapse;
						font-size: 13px;
						margin-top: 20px;
					}
					th {
						text-align: left;
						padding: 10px;
						border-bottom: 2px solid #ccc;
						font-size: 14px;
						font-weight: 600;
						color: #333;
					}
					td {
						padding: 10px;
						border-bottom: 1px solid #eee;
					}
					tr:nth-child(even) {
						background-color: #f9f9f9;
					}
					tr:hover {
						background-color: #f1f1f1;
					}
					a {
						color: #0073aa;
						text-decoration: none;
					}
					a:hover {
						color: #005177;
						text-decoration: underline;
					}
					.image-count {
						text-align: center;
					}
				</style>
			</head>
			<body>
				<div id="top">
					<h1>XML Sitemap</h1>
					<p>
						This is an XML Sitemap generated by Januar001 SEO Sitemap Generator. <br />
						You can find more information about XML sitemaps on <a href="https://sitemaps.org">sitemaps.org</a>.
					</p>
				</div>
				<div id="content">
					<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
						<p>This XML Sitemap Index file contains <strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></strong> sitemaps.</p>
						<table>
							<thead>
								<tr>
									<th>Sitemap</th>
									<th>Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
									<tr>
										<td>
											<xsl:variable name="itemURL">
												<xsl:value-of select="sitemap:loc"/>
											</xsl:variable>
											<a href="{$itemURL}">
												<xsl:value-of select="sitemap:loc"/>
											</a>
										</td>
										<td>
											<xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)),concat(' ', substring(sitemap:lastmod,20,6)))"/>
										</td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>
					<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &lt; 1">
						<p>This XML Sitemap contains <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong> URLs.</p>
						<table>
							<thead>
								<tr>
									<th>URL</th>
									<th>Images</th>
									<th>Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:urlset/sitemap:url">
									<tr>
										<td>
											<xsl:variable name="itemURL">
												<xsl:value-of select="sitemap:loc"/>
											</xsl:variable>
											<a href="{$itemURL}">
												<xsl:value-of select="sitemap:loc"/>
											</a>
										</td>
										<td class="image-count">
											<xsl:value-of select="count(image:image)"/>
										</td>
										<td>
											<xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)),concat(' ', substring(sitemap:lastmod,20,6)))"/>
										</td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
